package application.exceptions

class UserAlreadyExists : Exception()
class UserNotFound: Exception()
